from . import setu_class
from . import setu_school
from . import setu_student
from . import setu_subject
from . import setu_teacher
from . import setu_admission_form
from . import setu_academic_year
from . import setu_academic_month
from . import setu_class_room
from . import setu_standard_medium
from . import setu_standard_division
from . import setu_standard_standard
from . import setu_student_cast
from . import setu_grade
from . import setu_mother_tongue
from . import setu_grade_line
