# -*- coding: utf-8 -*
{
    'name': 'setu_school_management',
    'version': '16.1',
    'depends': ['contact', 'mail'],
    'data': [
        'security/school_groups.xml',
        'security/ir.model.access.csv',
        'report/report_from_wizard_school.xml',
        'wizard/setu_school_wizard_views.xml',
        'views/setu_school_views.xml',
        'views/setu_teacher_views.xml',
        'views/setu_class_views.xml',
        'views/setu_subject_views.xml',
        'views/setu_student_views.xml',
        'views/setu_admission_form_views.xml',
        'views/setu_academic_year_views.xml',
        'views/setu_academic_month_views.xml',
        'views/setu_class_room_views.xml',
        'views/setu_standard_medium_views.xml',
        'views/setu_standard_division_views.xml',
        'views/setu_standard_standard_views.xml',
        'views/setu_student_cast_views.xml',
        'views/setu_grade_views.xml',
        'views/setu_grade_line_views.xml',
        'views/setu_mother_toungue_views.xml',
        'views/res_users_views.xml',
        'report/school_report.xml',
        'report/student_template.xml',
        'report/mrp_inherit_teacher.xml',
    ],
    # 'assets': {'web.assets_backend': ['setu_school_management/report/mrp_inherit_teacher.xml']},
}
