# -*- coding: utf-8 -*
{
    'name': 'Setu School Management',
    'version': '1.1',
    'depends': ['contact'],
    'data':[
        'security/ir.model.access.csv',
        'views/setu_school_views.xml',
        'views/setu_teacher_views.xml',
        'views/setu_class_views.xml',
        'views/setu_subject_views.xml',
        'views/setu_student_views.xml',
        'views/setu_admission_form_views.xml',
        'views/setu_academic_year_views.xml',
        'views/setu_academic_month_views.xml',
        'views/setu_class_room_views.xml',
        'views/setu_standard_medium_views.xml',
        'views/setu_standard_division_views.xml',
        'views/setu_standard_standard_views.xml',
        'views/setu_student_cast_views.xml',
        'views/setu_grade_views.xml',
        'views/setu_grade_line_views.xml',
        'views/setu_mother_toungue_views.xml',
    ],
}