{
    'name':'Contact',
    'version':'16.0',
    'data':[
        'security/ir.model.access.csv',
        'views/country_views.xml',
        'views/city_views.xml',
        'views/state_views.xml',
        'views/customer_views.xml'
    ]
}